//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizlearnTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Custormer
    {
        public int mc_seq { get; set; }
        public string mc_fname { get; set; }
        public string mc_lname { get; set; }
        public string mc_fullname { get; set; }
        public string mc_mobile { get; set; }
        public string mc_address { get; set; }
        public string mc_email { get; set; }
        public System.DateTime mc_dob { get; set; }
        public string mc_createby { get; set; }
        public System.DateTime mc_create_dt { get; set; }
        public decimal mc_isverify { get; set; }
        public string mc_password { get; set; }
    }
}
